### ISSUE TITLE
UNK problem

### ISSUE THREAD

**Issue by ttslr** [shtoshni92/g2p#2]
Excuse me！
I cannot find any operation for the UNK word.

Can you tell me the process method for UNK?

Thank you very much!

Best Regards!

**Comment by shtoshni** [comment]
Well there are no UNK words in G2P since it operates at character level.

**Comment by ttslr** [comment]
Thanks for your reply!


Best Regards!
On 6/27/2018 21:30，Shubham Toshniwal<notifications@github.com> wrote：

Well there are no UNK words in G2P since it operates at character level.
